INSERT INTO products (product_name, category, product_description, image_file, price) VALUES
    ('Ballpoint Pens - Pack of 10', 'Writing Supplies', 'Black ink ballpoint pens for everyday use.', 'ballpoint_pens.jpg', 5),
    ('Mechanical Pencils - Pack of 12', 'Writing Supplies', '0.7mm mechanical pencils with refillable lead.', 'mechanical_pencils.jpg', 8),
    ('Highlighters - Pack of 6', 'Writing Supplies', 'Assorted color highlighters for notes and documents.', 'highlighters.jpg', 6),
    ('Printer Paper - 500 Sheets', 'Paper Products', 'Standard 8.5 x 11 inch white printer paper.', 'printer_paper.jpg', 9),
    ('Sticky Notes - Pack of 12', 'Paper Products', 'Self-adhesive notes for reminders and organization.', 'sticky_notes.jpg', 7),
    ('Legal Pads - Pack of 3', 'Paper Products', 'Yellow lined legal pads for note taking.', 'legal_pads.jpg', 6),
    ('Paper Clips - Box of 100', 'Desk Accessories', 'Standard silver paper clips for organizing papers.', 'paper_clips.jpg', 3),
    ('Binder Clips - Pack of 24', 'Desk Accessories', 'Medium-sized black binder clips.', 'binder_clips.jpg', 4),
    ('Stapler', 'Desk Accessories', 'Standard desktop stapler with durable metal construction.', 'stapler.jpg', 12),
    ('Staples - Box of 5000', 'Desk Accessories', 'Standard staples compatible with most staplers.', 'staples.jpg', 4),
    ('Clipboard', 'Desk Accessories', 'Hardboard clipboard with metal clip.', 'clipboard.jpg', 8),
    ('Scissors', 'Desk Accessories', '8-inch stainless steel office scissors.', 'scissors.jpg', 7),
    ('Desk Organizer', 'Desk Accessories', 'Multi-compartment organizer for office supplies.', 'desk_organizer.jpg', 15),
    ('File Folders - Pack of 20', 'Organization', 'Manila folders for filing documents.', 'file_folders.jpg', 10),
    ('3-Ring Binder - 2 Inch', 'Organization', 'Durable binder for storing documents.', 'three_ring_binder.jpg', 11),
    ('Hanging File Folders - Pack of 10', 'Organization', 'Colored hanging folders for file cabinets.', 'hanging_folders.jpg', 13),
    ('Whiteboard Markers - Pack of 8', 'Writing Supplies', 'Dry erase markers with assorted colors.', 'whiteboard_markers.jpg', 9),
    ('Correction Tape - Pack of 3', 'Writing Supplies', 'Easy-to-use correction tape for mistakes.', 'correction_tape.jpg', 5),
    ('Tape Dispenser', 'Desk Accessories', 'Weighted tape dispenser with refillable roll.', 'tape_dispenser.jpg', 9),
    ('Shipping Labels - Pack of 100', 'Paper Products', 'Printable adhesive labels for mailing and organization.', 'shipping_labels.jpg', 14);