INSERT INTO products (product_name, category, product_description, image_file, quantity, price) VALUES
    ('Ballpoint Pens', 'Writing Supplies', 'Black ink ballpoint pens for everyday use.', 'ballpoint_pens.jpg', 10, 8),
    ('Mechanical Pencils', 'Writing Supplies', '0.7mm mechanical pencils with refillable lead.', 'mechanical_pencils.jpg', 12, 10),
    ('Highlighters', 'Writing Supplies', 'Assorted color highlighters for notes and documents.', 'highlighters.jpg', 6, 9),
    ('Printer Paper', 'Paper Products', 'Standard 8.5 x 11 inch white printer paper.', 'printer_paper.jpg', 500, 22),
    ('Sticky Notes', 'Paper Products', 'Self-adhesive notes for reminders and organization.', 'sticky_notes.jpg', 12, 11),
    ('Legal Pads', 'Paper Products', 'Yellow lined legal pads for note taking.', 'legal_pads.jpg', 3, 9),
    ('Paper Clips', 'Desk Accessories', 'Standard silver paper clips for organizing papers.', 'paper_clips.jpg', 100, 6),
    ('Binder Clips', 'Desk Accessories', 'Medium-sized black binder clips.', 'binder_clips.jpg', 24, 7),
    ('Stapler', 'Desk Accessories', 'Standard desktop stapler with durable metal construction.', 'stapler.jpg', 1, 18),
    ('Staples', 'Desk Accessories', 'Standard staples compatible with most staplers.', 'staples.jpg', 5000, 12),
    ('Clipboard', 'Desk Accessories', 'Hardboard clipboard with metal clip.', 'clipboard.jpg', 1, 10),
    ('Scissors', 'Desk Accessories', '8-inch stainless steel office scissors.', 'scissors.jpg', 1, 13),
    ('Desk Organizer', 'Desk Accessories', 'Multi-compartment organizer for office supplies.', 'desk_organizer.jpg', 1, 28),
    ('File Folders', 'Organization', 'Manila folders for filing documents.', 'file_folders.jpg', 20, 16),
    ('3-Ring Binder - 2 Inch', 'Organization', 'Durable binder for storing documents.', 'three_ring_binder.jpg', 1, 12),
    ('Hanging File Folders', 'Organization', 'Colored hanging folders for file cabinets.', 'hanging_folders.jpg', 10, 19),
    ('Whiteboard Markers', 'Writing Supplies', 'Dry erase markers with assorted colors.', 'whiteboard_markers.jpg', 8, 14),
    ('Correction Tape', 'Writing Supplies', 'Easy-to-use correction tape for mistakes.', 'correction_tape.jpg', 3, 8),
    ('Tape Dispenser', 'Desk Accessories', 'Weighted tape dispenser with refillable roll.', 'tape_dispenser.jpg', 1, 15),
    ('Shipping Labels', 'Paper Products', 'Printable adhesive labels for mailing and organization.', 'shipping_labels.jpg', 100, 24);